# Limpiador del forms de asesorias - CMAT
***Instrucciones:***



1.   Sube tu archivo excel a este notebook (si no sabes como subirlo:)
[Tutorial](https://www.youtube.com/shorts/I9zT-dC4Lw8)
2.   Donde subiste tu archivo hay 3 puntitos, dale click y selecciona: "copy path"
3.   Corre las celdas de codigo y haz lo que se indica
4. Una vez ejecutada la ultima celda de codigo, se va a tardar unos minutos en darte el nuevo archivo, este se encuentra en el mismo apartado en donde subiste el excel inicial

In [ ]:
import pandas as pd

path = input("Introduce el path del archivo Excel (copia y pega, como en las instrucciones): ").strip()

try:
    df = pd.read_excel(path)
    print("Archivo cargado correctamente")

except FileNotFoundError:
    print("Error: No se encontró el archivo en la ruta proporcionada.")

except ValueError:

    print("Error: El archivo no parece ser un archivo Excel válido.")

except Exception as e:
    print(f"Ocurrió un error al cargar el archivo: {e}")

Introduce el path del archivo Excel (copia y pega, como en las instrucciones): /content/ASESORIAS PABLO 24 VERANO.xlsx
Archivo cargado correctamente

In [ ]:
# VERIFICA que si sea este archivo
df

,ID,Hora de inicio,Hora de finalización,Correo electrónico,Nombre,Total de puntos,Comentarios del cuestionario,Hora de la última modificación,CARRERA,Escanear el ID del estudiante,...,Comentarios: Estadística para Negocios: Tema de la asesoría,Otro,Puntos: Otro,Comentarios: Otro,Estadística para Ciencias de la Salud,Puntos: Estadística para Ciencias de la Salud,Comentarios: Estadística para Ciencias de la Salud,Otros,Puntos: Otros,Comentarios: Otros
0,1128,2024-05-23 11:07:58,2024-05-23 11:51:52,pablo.silvana@udlap.mx,Pablo Silva Norena,NaN,NaN,NaN,LIM - INGENIERÍA MECÁNICA,180622,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1129,2024-05-24 09:58:55,2024-05-24 10:02:39,abraham.medinaca@udlap.mx,Abraham Medina Coria,NaN,NaN,NaN,LEC - ECONOMÍA,176087,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1130,2024-05-24 10:11:48,2024-05-24 10:12:39,abraham.medinaca@udlap.mx,Abraham Medina Coria,NaN,NaN,NaN,LBC - BIOQUÍMICA CLÍNICA,177539,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1131,2024-05-24 10:14:35,2024-05-24 10:27:55,abraham.medinaca@udlap.mx,Abraham Medina Coria,NaN,NaN,NaN,LCN - CIENCIAS DE LA NUTRICIÓN,179382,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1132,2024-05-24 10:27:56,2024-05-24 10:28:29,abraham.medinaca@udlap.mx,Abraham Medina Coria,NaN,NaN,NaN,LCN - CIENCIAS DE LA NUTRICIÓN,179262,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2422,3550,2024-11-27 19:00:39,2024-11-29 10:08:27,braulio.martinezas@udlap.mx,Braulio Martinez Animas,NaN,NaN,NaN,LIS - INGENIERÍA EN SISTEMAS COMPUTACIONALES,183759,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2423,3551,2024-11-29 11:16:25,2024-11-29 11:41:19,samantha.herreravs@udlap.mx,Samantha Herrera Vargas,NaN,NaN,NaN,LAT - ACTUARÍA,183876,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2424,3552,2024-11-29 15:03:12,2024-11-29 15:06:51,jorge.blasas@udlap.mx,Jorge Andres Blas Alanis,NaN,NaN,NaN,LNI - ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES,178689,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2425,3553,2024-11-29 15:28:16,2024-11-29 15:28:34,jorge.blasas@udlap.mx,Jorge Andres Blas Alanis,NaN,NaN,NaN,LAD - ADMINISTRACIÓN DE EMPRESAS,181349,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2426,3554,2024-11-29 15:28:36,2024-11-29 15:28:49,jorge.blasas@udlap.mx,Jorge Andres Blas Alanis,NaN,NaN,NaN,LNI - ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES,181162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
def column_otros(df):

  re_name = {

      "Hora de inicio": "fecha",
      "Escanear el ID del estudiante": "id",
      "CARRERA": "carrera",
      "Indicar el semestre que actualmente cursa el estudiante": "semestre",
      # "Elija su nombre como profesor que imparte la asesoría": "profesor",
      "Elija la materia de la asesoría que imparte": "materia"
  }


  df = df.rename(columns = re_name)
  idx_materia = df.columns.get_loc("materia")
  concat_df_temas = df.columns[idx_materia + 1:]

  df["tema"] = df[concat_df_temas].apply(lambda fila: " ".join(fila.dropna().astype(str)), axis=1)
  df = df.drop(columns = concat_df_temas)

  interest_columns = ["fecha", "id", "carrera", "semestre", "profesor", "materia", "tema"]
  df = df[[col for col in interest_columns if col in df.columns]]
  df["periodo"] = "P" # CAMBIALO DEPENDIENDO SI ES P: Primavera o O: otoño

  # df.to_excel("clean_excel.xlsx", index = False)
  return df


df = column_otros(df)
df

,fecha,id,carrera,semestre,materia,periodo
0,2024-05-23 11:07:58,180622,LIM - INGENIERÍA MECÁNICA,3,Cálculo I,P
1,2024-05-24 09:58:55,176087,LEC - ECONOMÍA,3,Cálculo II,P
2,2024-05-24 10:11:48,177539,LBC - BIOQUÍMICA CLÍNICA,4,Estadística Inferencial,P
3,2024-05-24 10:14:35,179382,LCN - CIENCIAS DE LA NUTRICIÓN,3,Estadística Inferencial,P
4,2024-05-24 10:27:56,179262,LCN - CIENCIAS DE LA NUTRICIÓN,3,Estadística Inferencial,P
...,...,...,...,...,...,...
2422,2024-11-27 19:00:39,183759,LIS - INGENIERÍA EN SISTEMAS COMPUTACIONALES,1,Matemáticas Universitarias,P
2423,2024-11-29 11:16:25,183876,LAT - ACTUARÍA,1,Matemáticas Universitarias,P
2424,2024-11-29 15:03:12,178689,LNI - ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES,1,Matemáticas Universitarias,P
2425,2024-11-29 15:28:16,181349,LAD - ADMINISTRACIÓN DE EMPRESAS,3,Cálculo I,P
2426,2024-11-29 15:28:36,181162,LNI - ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES,3,Cálculo I,P

# **POR AMOR A DIOS CHECA QUE LOS DATOS ESTEN BIEN ANTES DE PEGARLOS A LA BASE ORIGINAL!**